<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCG8Zf87\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCG8Zf87/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCG8Zf87.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCG8Zf87\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerCG8Zf87\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'CG8Zf87',
    'container.build_id' => 'e506079c',
    'container.build_time' => 1655487163,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCG8Zf87');
